trigger:
  branches:
    include:
      - main  # Replace with your branch name or pattern

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Lint
  jobs:
  - job: LintCode
    displayName: Lint Code
    steps:
    - script: |
        az bicep build --file main.bicep
      name: LintBicepCode
      displayName: Run Bicep

- stage: Validate
  jobs:
  - job: ValidateBicepCode
    displayName: Validate Bicep Code
    steps:
    - task: AzureCLI@2
      name: RunPreflightValidation
      displayName: Run Preflight Validation
      inputs:
        azureSubscription: 'azure_srv'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment group validate --resource-group Test1-RG \
          --template-file main.bicep \
          --parameters @Linux_parameter.json

- stage: Deploy
  jobs:
  - job: Deploy
    displayName: Deploy to Azure
    steps:
    - task: AzureCLI@2
      name: Deploy
      displayName: Deploy to Azure
      inputs:
        azureSubscription: 'azure_srv'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment group create --name $(Build.BuildNumber) \
          --resource-group Test1-RG \
          --template-file main.bicep \
          --parameters @Linux_parameter.json
