trigger:
  branches:
    include:
      - main  # Replace with your branch name or pattern

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Lint
  jobs:
  - job: LintCode
    displayName: Lint Code
    steps:
    - script: |
        az bicep build --file main.bicep
      name: LintBicepCode
      displayName: Run Bicep Lint

- stage: Validate
  jobs:
  - job: ValidateBicepCode
    displayName: Validate Bicep Code
    steps:
    # Retrieve public IP and add it to the Ansible inventory directly
    - task: Bash@3
      displayName: Retrieve Public IP and Update Ansible Inventory
      inputs:
        targetType: 'inline'
        script: |
          PUBLIC_IP=$(az network public-ip show --resource-group sandy-RG --name public-Ip --query ipAddress -o tsv)
          echo "$PUBLIC_IP ansible_user=azureuser ansible_password=Sandy@1234" >> inventory
          cat inventory
